django/controlpanel/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from inforecords.views import *

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^certificaat/genereer/(.+)/(.+).zip$', genereer),
    (r'^maakconfig$', maakconfig),
    (r'^$', direct_to_template, {'template': 'frontpage.html'}),
    (r'^config/nagios$', create_nagios_config),
)

publicdb/raw_data/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'data'
urlpatterns = [
    path('', RedirectView.as_view(url='download', permanent=False)),
    path('download/', views.download_form, name='download_form'),
    path('download/<int:station_number>/<str:start>/<str:end>/', views.download_form, name='download_form'),
    path('download/coincidences/', views.coincidences_download_form, name='coincidences_download_form'),
    path(
        'download/coincidences/<str:start>/<str:end>/',
        views.coincidences_download_form,
        name='coincidences_download_form',
    ),
    path('rpc', views.call_xmlrpc, name='rpc'),
    path('<int:station_number>/events/', views.download_data, {'data_type': 'events'}, name='events'),
    path('<int:station_number>/weather/', views.download_data, {'data_type': 'weather'}, name='weather'),
    path('<int:station_number>/singles/', views.download_data, {'data_type': 'singles'}, name='singles'),
    path(
        'knmi/lightning/<int:lightning_type>/',
        views.download_data,
        {'data_type': 'lightning'},
        name='lightning',
    ),
    path('network/coincidences/', views.download_coincidences, name='coincidences'),
]

publicdb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView

from .inforecords.views import create_datastore_config

urlpatterns = [
    path('', RedirectView.as_view(url='show/stations', permanent=False)),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('api/', include('publicdb.api.urls')),
    path('show/', include('publicdb.status_display.urls')),
    path('maps/', include('publicdb.maps.urls')),
    path('layout/', include('publicdb.station_layout.urls')),
    path('analysis-session/', include('publicdb.analysissessions.urls')),
    path('software-updates/', include('publicdb.updates.urls')),
    path('raw_data/', include('publicdb.raw_data.urls', namespace='raw_data')),
    path('data/', include('publicdb.raw_data.urls')),
    path('config/datastore', create_datastore_config, name='datastore_config'),
    path('admin/', admin.site.urls),
]

publicdb/raw_data/forms.py
from django import forms
from django.core.exceptions import ValidationError

from ..inforecords.models import Cluster, Station

TYPES = [('events', 'Events'), ('weather', 'Weather'), ('lightning', 'Lightning'), ('singles', 'Singles')]

LGT_TYPES = [
    ('0', 'Single-point'),
    ('1', 'Cloud-cloud'),
    ('2', 'Cloud-cloud mid'),
    ('3', 'Cloud-cloud end'),
    ('4', 'Cloud-ground'),
    ('5', 'Cloud-ground return'),
]

FILTER = [('network', 'Network'), ('cluster', 'Cluster'), ('stations', 'Stations')]


class DataDownloadForm(forms.Form):
    data_type = forms.ChoiceField(choices=TYPES, widget=forms.RadioSelect())
    station_events = forms.ModelChoiceField(
        Station.objects.filter(summaries__num_events__isnull=False).distinct(),
        empty_label='---------',
        required=False,
    )
    station_weather = forms.ModelChoiceField(
        Station.objects.filter(summaries__num_weather__isnull=False).distinct(),
        empty_label='---------',
        required=False,
    )
    lightning_type = forms.ChoiceField(choices=LGT_TYPES, initial=4, required=False)
    station_singles = forms.ModelChoiceField(
        Station.objects.filter(summaries__num_singles__isnull=False).distinct(),
        empty_label='---------',
        required=False,
    )
    start = forms.DateTimeField(help_text="e.g. '2013-5-17', or '2013-5-17 12:45'")
    end = forms.DateTimeField(help_text="e.g. '2013-5-18', or '2013-5-18 9:05'")
    download = forms.BooleanField(initial=True, required=False)

    def clean(self):
        """Check the choices to ensure the combination of choices are valid"""

        cleaned_data = super().clean()
        data_type = cleaned_data.get('data_type')

        for station_data_type in ['events', 'weather', 'singles']:
            station_field = f'station_{station_data_type}'
            if data_type == station_data_type:
                station = cleaned_data.get(station_field)
                if not station:
                    self.add_error(station_field, 'Choose a station')
                else:
                    cleaned_data['station'] = station
            else:
                del cleaned_data[station_field]
        return cleaned_data


class CoincidenceDownloadForm(forms.Form):
    filter_by = forms.ChoiceField(choices=FILTER, widget=forms.RadioSelect())
    cluster = forms.ModelChoiceField(Cluster.objects.filter(parent=None), empty_label='---------', required=False)
    stations = forms.CharField(help_text="e.g. '103, 104, 105'", required=False)
    start = forms.DateTimeField(help_text="e.g. '2014-4-5', or '2014-4-18 12:45'")
    end = forms.DateTimeField(help_text="e.g. '2014-4-29', or '2014-04-30 9:05'")
    n = forms.IntegerField(min_value=2, help_text='Minimum number of events in a coincidence')
    download = forms.BooleanField(initial=True, required=False)

    def clean(self):
        """Check the choices to ensure the combination of choices are valid"""

        cleaned_data = super().clean()
        filter_by = cleaned_data.get('filter_by')
        if filter_by == 'network':
            del cleaned_data['cluster']
            del cleaned_data['stations']
        elif filter_by == 'cluster':
            del cleaned_data['stations']
            cluster = cleaned_data.get('cluster')
            if not cluster:
                self.add_error('cluster', ValidationError('Choose a cluster.', 'invalid_choice'))
        elif filter_by == 'stations':
            del cleaned_data['cluster']
            msg = None
            stations = cleaned_data.get('stations')
            if not stations:
                msg = ValidationError('A list of stations is required.', 'required')
            else:
                try:
                    s_numbers = [int(x) for x in stations.strip('[]()').split(',')]
                except ValueError:
                    msg = ValidationError('Incorrect station entry.', 'incorrect_entry')
                else:
                    if len(s_numbers) < cleaned_data.get('n'):
                        msg = ValidationError('Enter at least N stations.', 'too_few')
                    elif len(s_numbers) > 30:
                        msg = ValidationError('Exceeded limit of 30 stations.', 'too_many')
                    elif Station.objects.filter(number__in=s_numbers).count() != len(s_numbers):
                        msg = ValidationError('Invalid station numbers.', 'invalid_choices')
            if msg is not None:
                self.add_error('stations', msg)

        return cleaned_data

publicdb/raw_data/views.py
import csv
import datetime
import os
import tempfile
import urllib.error
import urllib.parse
import urllib.request

from io import StringIO
from urllib.parse import urljoin
from xmlrpc.server import SimpleXMLRPCDispatcher

import dateutil.parser
import tables

from numpy import char, column_stack, degrees, empty, isnan, where

from django.conf import settings
from django.db.models import Q
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect, StreamingHttpResponse
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from sapphire import CoincidenceQuery, datetime_to_gps

from ..histograms import esd
from ..histograms.models import NetworkSummary, Summary
from ..inforecords.models import Cluster, Station
from . import knmi_lightning
from .date_generator import single_day_ranges
from .forms import CoincidenceDownloadForm, DataDownloadForm

dispatcher = SimpleXMLRPCDispatcher()


MIME_PLAIN = 'text/plain'
MIME_TSV = 'text/tab-separated-values'
MIME_XML = 'text/xml'


class SingleLineStringIO:
    """Very limited file-like object buffering a single line."""

    def write(self, line):
        self.line = line


@csrf_exempt
def call_xmlrpc(request):
    """Dispatch XML-RPC requests."""

    if request.method == 'POST':
        # Process XML-RPC call
        response = HttpResponse(content_type=MIME_XML)
        response.write(dispatcher._marshaled_dispatch(request.body))
        response['Content-length'] = str(len(response.content))
        return response
    else:
        # Show documentation on available methods
        response = HttpResponse()
        template = loader.get_template('raw_data/xmlrpc.html')
        methods = [
            {'name': method, 'help': dispatcher.system_methodHelp(method)} for method in dispatcher.system_listMethods()
        ]
        context = {'methods': methods}
        response.write(template.render(context))
        return response


def xmlrpc(uri):
    """A decorator for XML-RPC functions."""

    def register_xmlrpc(fn):
        dispatcher.register_function(fn, uri)
        return fn

    return register_xmlrpc


@xmlrpc('hisparc.get_data_url')
def get_data_url(station_number, date, get_blobs=False):
    """Return a link to a file containing requested data

    Based on the given parameters, copy requested data to a temporary file
    and provide a link to download that file.

    :param station_number: the HiSPARC station number
    :param date: a xmlrpc.client.DateTime instance; retrieve events from this day

    """
    date = date.timetuple()

    datafile = get_raw_datafile(date)
    station_node = get_station_node(datafile, station_number)
    target = get_target()

    if get_blobs:
        datafile.copy_node(station_node, target.root, recursive=True)
    else:
        datafile.copy_node(station_node, target.root, recursive=False)
        target_node = target.get_node('/', station_node._v_name)
        for node in station_node:
            if node.name != 'blobs':
                datafile.copy_node(node, target_node)

    url = urljoin(settings.MEDIA_URL, 'raw_data/')
    url = urljoin(url, os.path.basename(target.filename))

    datafile.close()
    target.close()

    return url


def get_raw_datafile(date):
    """Return a reference to the raw data file on a specified date"""

    dir = os.path.join(settings.DATASTORE_PATH, f'{date.tm_year}/{date.tm_mon}')
    name = os.path.join(dir, f'{date.tm_year}_{date.tm_mon}_{date.tm_mday}.h5')
    try:
        datafile = tables.open_file(name, 'r')
    except OSError:
        raise ValueError('No data for that date')

    return datafile


def get_station_node(datafile, station_number):
    """Return the requested station's node"""

    station = f'station_{station_number}'

    for cluster in datafile.list_nodes('/hisparc'):
        if station in cluster:
            return datafile.get_node(cluster, station)

    raise ValueError('No data available for this station on that date')


def get_target():
    """Return a reference to a download target file"""

    dir = os.path.join(settings.MEDIA_ROOT, 'raw_data')
    with tempfile.NamedTemporaryFile(suffix='.h5', dir=dir, delete=False) as file:
        pass
    # FIXME (for debugging only, sets extra permissions)
    # os.chmod(file.name, 0644)
    return tables.open_file(file.name, 'w')


def download_form(request, station_number=None, start=None, end=None):
    if request.GET:
        form = DataDownloadForm(request.GET)
        if form.is_valid():
            start = form.cleaned_data['start']
            end = form.cleaned_data['end']
            download = form.cleaned_data['download']
            data_type = form.cleaned_data['data_type']
            query_string = urllib.parse.urlencode({'start': start, 'end': end, 'download': download})
            if data_type == 'lightning':
                lightning_type = form.cleaned_data['lightning_type']
                url = reverse('data:lightning', kwargs={'lightning_type': lightning_type})
            else:
                station = form.cleaned_data['station']
                url = reverse(f'data:{data_type}', kwargs={'station_number': station.number})
            return HttpResponseRedirect(f'{url}?{query_string}')
    else:
        if station_number:
            station = get_object_or_404(Station, number=station_number)
        else:
            station = None
        form = DataDownloadForm(
            initial={
                'station_events': station,
                'station_weather': station,
                'station_singles': station,
                'start': start,
                'end': end,
                'data_type': 'events',
            },
        )

    return render(request, 'raw_data/data_download.html', {'form': form})


def download_data(request, data_type='events', station_number=None, lightning_type=None):
    """Download data.

    :param data_type: (optional) choose between event, weather, and lightning data
    :param station_number: (optional) station number, required for event and weather data
    :param lightning_type: (optional) lightning type, required for lightning data
    :param start: (optional, GET) start of data range
    :param end: (optional, GET) end of data range
    :param download: (optional, GET) download the tsv

    """
    if data_type in ['events', 'weather', 'singles']:
        station = get_object_or_404(Station, number=station_number)

    yesterday = datetime.date.today() - datetime.timedelta(days=1)
    yesterday = datetime.datetime.combine(yesterday, datetime.time())

    try:
        if 'start' in request.GET:
            start = dateutil.parser.parse(request.GET['start'])
        else:
            start = yesterday

        if 'end' in request.GET:
            end = dateutil.parser.parse(request.GET['end'])
        else:
            end = start + datetime.timedelta(days=1)
    except ValueError:
        error_msg = 'Incorrect optional parameters (start [datetime], end [datetime])'
        return HttpResponseBadRequest(error_msg, content_type=MIME_PLAIN)

    timerange_string = prettyprint_timerange(start, end)
    if data_type == 'events':
        tsv_output = generate_events_as_tsv(station, start, end)
        filename = f'events-s{station_number}-{timerange_string}.tsv'
    elif data_type == 'weather':
        tsv_output = generate_weather_as_tsv(station, start, end)
        filename = f'weather-s{station_number}-{timerange_string}.tsv'
    elif data_type == 'singles':
        tsv_output = generate_singles_as_tsv(station, start, end)
        filename = f'singles-s{station_number}-{timerange_string}.tsv'
    elif data_type == 'lightning':
        if lightning_type not in list(range(6)):
            msg = 'Incorrect lightning type, should be a value between 0-5'
            return HttpResponseBadRequest(msg, content_type=MIME_PLAIN)
        tsv_output = generate_lightning_as_tsv(lightning_type, start, end)
        filename = f'lightning-knmi-{timerange_string}.tsv'

    response = StreamingHttpResponse(tsv_output, content_type=MIME_TSV)

    if request.GET.get('download', False) in ['true', 'True']:
        content_disposition = f'attachment; filename="{filename}"'
    else:
        content_disposition = f'inline; filename="{filename}"'
    response['Content-Disposition'] = content_disposition
    response['Access-Control-Allow-Origin'] = '*'

    return response


def generate_events_as_tsv(station, start, end):
    """Render TSV output as an iterator."""

    template = loader.get_template('raw_data/event_data.tsv')
    context = {'station': station, 'start': start, 'end': end}

    yield template.render(context)

    events_returned = False

    events_reconstructions = get_events_from_esd_in_range(station, start, end)
    for events, reconstructions in events_reconstructions:
        if not len(events):
            continue
        dt = events['timestamp'].astype('datetime64[s]')
        data = column_stack(
            [
                dt.astype('datetime64[D]'),
                [value.time() for value in dt.tolist()],
                events['timestamp'],
                events['nanoseconds'],
                events['pulseheights'][:, 0],
                events['pulseheights'][:, 1],
                events['pulseheights'][:, 2],
                events['pulseheights'][:, 3],
                events['integrals'][:, 0],
                events['integrals'][:, 1],
                events['integrals'][:, 2],
                events['integrals'][:, 3],
                clean_float_array(events['n1']),
                clean_float_array(events['n2']),
                clean_float_array(events['n3']),
                clean_float_array(events['n4']),
                clean_float_array(events['t1']),
                clean_float_array(events['t2']),
                clean_float_array(events['t3']),

publicdb/raw_data/templates/raw_data/coincidences_download.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
HiSPARC coincidences download form
{% endblock %}

{% block head_styles %}
<link rel="stylesheet" href="{% static 'styles/download_form.css' %}">
{% endblock %}

{% block head %}
<script>
    $(document).ready(function () {
        disable_stuff()
        // Show fields depending on filter choice
        $('[name=filter_by]').change(function() {disable_stuff()})
    });

    function disable_stuff() {
        if ($('[name=filter_by]:checked').val() == 'stations') {
            $('#id_cluster').prop("disabled", true);
            $('#id_stations').prop("disabled", false);}
        else if ($('[name=filter_by]:checked').val() == 'cluster') {
            $('#id_cluster').prop("disabled", false);
            $('#id_stations').prop("disabled", true);}
        else {
            $('#id_cluster').prop("disabled", true);
            $('#id_stations').prop("disabled", true);}
    };
</script>
{% endblock %}

{% block content %}

<div id="header"><h2>Coincidences download form</h2></div>

<form action="{% url 'data:coincidences_download_form' %}" method="get">
    <p>
        {{ form.filter_by.errors }}
        {{ form.cluster.errors }}
        {{ form.stations.errors }}
        {{ form.filter_by.label_tag }}
    </p>
    <ul>
        <li>{{ form.filter_by.0 }}</li>
        <li>
            {{ form.filter_by.1 }}:
            {{ form.cluster }}
            <span class="helptext">{{ form.cluster.help_text }}</span>
        </li>
        <li>
            {{ form.filter_by.2 }}:
            {{ form.stations }}
            <span class="helptext">{{ form.stations.help_text }}</span>
        </li>
    </ul>
    <p>
        {{ form.start.errors }}
        {{ form.start.label_tag }}
        {{ form.start }}
        <span class="helptext">{{ form.start.help_text }}</span>
    </p>
    <p>
        {{ form.end.errors }}
        {{ form.end.label_tag }}
        {{ form.end }}
        <span class="helptext">{{ form.end.help_text }}</span>
    </p>
    <p>
        {{ form.n.errors }}
        {{ form.n.label_tag }}
        {{ form.n }}
        <span class="helptext">{{ form.n.help_text }}</span>
    </p>
    <p>
        {{ form.download.errors }}
        {{ form.download.label_tag }}
        {{ form.download }}
        <span class="helptext">{{ form.download.help_text }}</span>
    </p>

    <input type="submit" value="Submit">
</form>

<p class="small">
    <a href="{% url 'data:download_form' %}">
        Switch to station data download form
    </a>
</p>

{% endblock %}

publicdb/raw_data/templates/raw_data/data_download.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
HiSPARC data download form
{% endblock %}

{% block head_styles %}
<link rel="stylesheet" href="{% static 'styles/download_form.css' %}">
{% endblock %}

{% block head %}
<script>
    $(document).ready(function () {
        hide_stuff()
        // Show fields depending on filter choice
        $('[name=data_type]').change(function() {hide_stuff()})
    });

    function hide_stuff() {
        if ($('[name=data_type]:checked').val() == 'events') {
            $('[for=id_station_events]').show();
            $('[for=id_station_weather]').hide();
            $('[for=id_station_singles]').hide();
            $('[for=id_lightning_type]').hide();
            $('#id_station_events').show();
            $('#id_station_weather').hide();
            $('#id_station_singles').hide();
            $('#id_lightning_type').hide();}
        else if ($('[name=data_type]:checked').val() == 'weather') {
            $('[for=id_station_events]').hide();
            $('[for=id_station_weather]').show();
            $('[for=id_station_singles]').hide();
            $('[for=id_lightning_type]').hide();
            $('#id_station_events').hide();
            $('#id_station_weather').show();
            $('#id_station_singles').hide();
            $('#id_lightning_type').hide();}
        else if ($('[name=data_type]:checked').val() == 'singles') {
            $('[for=id_station_events]').hide();
            $('[for=id_station_weather]').hide();
            $('[for=id_station_singles]').show();
            $('[for=id_lightning_type]').hide();
            $('#id_station_events').hide();
            $('#id_station_weather').hide();
            $('#id_station_singles').show();
            $('#id_lightning_type').hide();}
        else if ($('[name=data_type]:checked').val() == 'lightning') {
            $('[for=id_station_events]').hide();
            $('[for=id_station_weather]').hide();
            $('[for=id_station_singles]').hide();
            $('[for=id_lightning_type]').show();
            $('#id_station_events').hide();
            $('#id_station_weather').hide();
            $('#id_station_singles').hide();
            $('#id_lightning_type').show();}
    };
</script>
{% endblock %}

{% block content %}

<div id="header"><h2>Data download form</h2></div>

<form action="{% url 'data:download_form' %}" method="get">
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

<p class="small">
    <a href="{% url 'data:coincidences_download_form' %}">
        Switch to coincidences download form
    </a>
</p>

<p class="reference">
    Lightning data obtained from Royal Netherlands Meteorological Institute.
    Available for 2004 up to and including 2015.
</p>

{% endblock %}

publicdb/raw_data/templates/raw_data/xmlrpc.html
<html>
<body>
XML-RPC Methods:
<ol>
    {% for method in methods %}
        <li>{{method.name}} {{method.help|linebreaks}}</li>
    {% endfor %}
</ol>
</body>
</html>