django/controlpanel/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from inforecords.views import *

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^certificaat/genereer/(.+)/(.+).zip$', genereer),
    (r'^maakconfig$', maakconfig),
    (r'^$', direct_to_template, {'template': 'frontpage.html'}),
    (r'^config/nagios$', create_nagios_config),
)

publicdb/station_layout/urls.py
from django.urls import path

from . import views

app_name = 'layout'
urlpatterns = [
    path('submit/', views.layout_submit, name='submit'),
    path('submit/validate/', views.validate_layout_submit, name='validate_submit'),
    path('confirm/<slug:hash>/', views.confirmed_layout, name='confirm'),
    path('review/<slug:hash>/', views.review_layout, name='review'),
    path('review/<slug:hash>/validate/', views.validate_review_layout, name='validate_review'),
]

publicdb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView

from .inforecords.views import create_datastore_config

urlpatterns = [
    path('', RedirectView.as_view(url='show/stations', permanent=False)),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('api/', include('publicdb.api.urls')),
    path('show/', include('publicdb.status_display.urls')),
    path('maps/', include('publicdb.maps.urls')),
    path('layout/', include('publicdb.station_layout.urls')),
    path('analysis-session/', include('publicdb.analysissessions.urls')),
    path('software-updates/', include('publicdb.updates.urls')),
    path('raw_data/', include('publicdb.raw_data.urls', namespace='raw_data')),
    path('data/', include('publicdb.raw_data.urls')),
    path('config/datastore', create_datastore_config, name='datastore_config'),
    path('admin/', admin.site.urls),
]

publicdb/station_layout/models.py
import os

from datetime import date
from textwrap import dedent

from django.core.mail import send_mail
from django.db import models

from ..histograms.models import Summary
from ..inforecords.models import Station


class StationLayout(models.Model):
    station = models.ForeignKey(Station, models.CASCADE, related_name='layouts')
    active_date = models.DateTimeField()
    detector_1_radius = models.FloatField()
    detector_1_alpha = models.FloatField()
    detector_1_height = models.FloatField()
    detector_1_beta = models.FloatField()
    detector_2_radius = models.FloatField()
    detector_2_alpha = models.FloatField()
    detector_2_height = models.FloatField()
    detector_2_beta = models.FloatField()
    detector_3_radius = models.FloatField(null=True, blank=True)
    detector_3_alpha = models.FloatField(null=True, blank=True)
    detector_3_height = models.FloatField(null=True, blank=True)
    detector_3_beta = models.FloatField(null=True, blank=True)
    detector_4_radius = models.FloatField(null=True, blank=True)
    detector_4_alpha = models.FloatField(null=True, blank=True)
    detector_4_height = models.FloatField(null=True, blank=True)
    detector_4_beta = models.FloatField(null=True, blank=True)

    class Meta:
        verbose_name = 'Station layout'
        verbose_name_plural = 'Station layouts'
        unique_together = ('station', 'active_date')
        ordering = ['station', 'active_date']
        get_latest_by = 'active_date'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            next_layout = StationLayout.objects.filter(
                station=self.station,
                active_date__gt=self.active_date,
            ).earliest()
            next_date = next_layout.active_date
        except StationLayout.DoesNotExist:
            next_date = date.today()
        if self.has_four_detectors:
            # Only for 4 detector stations
            summaries = Summary.objects.filter(station=self.station, date__gte=self.active_date, date__lt=next_date)
            for summary in summaries:
                if summary.num_events:
                    summary.needs_update_events = True
                    summary.save()

    @property
    def has_four_detectors(self):
        return self.detector_3_radius is not None and self.detector_4_radius is not None


class StationLayoutQuarantine(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    submit_date = models.DateTimeField(auto_now_add=True)
    email_verified = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)
    reviewed = models.BooleanField(default=False)

    hash_submit = models.CharField(max_length=32)
    hash_review = models.CharField(max_length=32)

    station = models.ForeignKey(Station, models.CASCADE, related_name='quarantined_layouts')
    active_date = models.DateTimeField()
    detector_1_radius = models.FloatField()
    detector_1_alpha = models.FloatField()
    detector_1_height = models.FloatField()
    detector_1_beta = models.FloatField()
    detector_2_radius = models.FloatField()
    detector_2_alpha = models.FloatField()
    detector_2_height = models.FloatField()
    detector_2_beta = models.FloatField()
    detector_3_radius = models.FloatField(null=True, blank=True)
    detector_3_alpha = models.FloatField(null=True, blank=True)
    detector_3_height = models.FloatField(null=True, blank=True)
    detector_3_beta = models.FloatField(null=True, blank=True)
    detector_4_radius = models.FloatField(null=True, blank=True)
    detector_4_alpha = models.FloatField(null=True, blank=True)
    detector_4_height = models.FloatField(null=True, blank=True)
    detector_4_beta = models.FloatField(null=True, blank=True)

    class Meta:
        verbose_name = 'Station layout quarantine'
        verbose_name_plural = 'Station layouts quarantine'

    def generate_hashes(self):
        hash_submit = os.urandom(16).encode('hex')
        hash_review = os.urandom(16).encode('hex')
        if StationLayoutQuarantine.objects.filter(hash_submit=hash_submit) or StationLayoutQuarantine.objects.filter(
            hash_review=hash_review,
        ):
            self.generate_hashes()
        else:
            self.hash_submit = hash_submit
            self.hash_review = hash_review

    def sendmail_submit(self):
        subject = 'HiSPARC station layout submission'
        message = dedent(
            f"""\
            Hello {self.name},

            Please click on this link to confirm your submission
            of a new layout for station {self.station}.
            https://data.hisparc.nl/layout/confirm/{self.hash_submit}/

            Greetings,
            The HiSPARC Team""",
        )
        sender = 'HiSPARC Project <hisparc@utah.edu>'
        send_mail(subject, message, sender, [self.email], fail_silently=False)

    def sendmail_review(self):
        subject = 'HiSPARC station layout review'
        message = dedent(
            f"""\
            Hello,

            A new station layout has been submitted for station {self.station}.
            Before it is stored in the database we request that you
            review the validity of the submission.
            Use the following link to view and either approve or
            decline the submission:
            https://data.hisparc.nl/layout/review/{self.hash_review}/

            Greetings,
            The HiSPARC Team""",
        )
        sender = 'HiSPARC Project <hisparc@utah.edu>'
        send_mail(subject, message, sender, ['hisparc@utah.edu'], fail_silently=False)

    def sendmail_accepted(self):
        subject = 'HiSPARC station layout accepted'
        message = dedent(
            f"""\
            Hello {self.name},

            The station layout which you submitted for station {self.station}
            has been approved by the reviewer.

            Greetings,
            The HiSPARC Team""",
        )
        sender = 'HiSPARC Project <hisparc@utah.edu>'
        send_mail(subject, message, sender, [self.email], fail_silently=False)

    def sendmail_declined(self):
        subject = 'HiSPARC station layout declined'
        message = dedent(
            f"""\
            Hello {self.name},

            The station layout which you submitted for station {self.station}
            has been declined by the reviewer.

            Greetings,
            The HiSPARC Team""",
        )
        sender = 'HiSPARC Project <hisparc@utah.edu>'
        send_mail(subject, message, sender, [self.email], fail_silently=False)

publicdb/station_layout/forms.py
from functools import partial

from django import forms

from ..inforecords.models import Station

# Distance and angle limits
DISTANCE_LIMITS = {'min_value': -60, 'max_value': 60}  # meters
ANGLE_LIMITS = {'min_value': -360, 'max_value': 360}  # degrees

radius_field = partial(forms.FloatField, **DISTANCE_LIMITS)
alpha_field = partial(forms.FloatField, **ANGLE_LIMITS)
height_field = partial(forms.FloatField, initial=0.0, **DISTANCE_LIMITS)
beta_field = partial(forms.FloatField, **ANGLE_LIMITS)


class StationLayoutQuarantineForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()

    station = forms.ModelChoiceField(queryset=Station.objects.filter(pcs__is_test=False).distinct())
    active_date = forms.DateTimeField(
        help_text="Date the detectors were placed in this configuration, e.g. '2010-5-17 12:45'.",
    )

    # Master detectors
    detector_1_radius = radius_field()
    detector_1_alpha = alpha_field()
    detector_1_height = height_field()
    detector_1_beta = beta_field()
    detector_2_radius = radius_field()
    detector_2_alpha = alpha_field()
    detector_2_height = height_field()
    detector_2_beta = beta_field()

    # Optional secondary detectors
    detector_3_radius = radius_field(required=False)
    detector_3_alpha = alpha_field(required=False)
    detector_3_height = height_field(required=False)
    detector_3_beta = beta_field(required=False)
    detector_4_radius = radius_field(required=False)
    detector_4_alpha = alpha_field(required=False)
    detector_4_height = height_field(required=False)
    detector_4_beta = beta_field(required=False)


class ReviewStationLayoutForm(forms.Form):
    approved = forms.BooleanField(required=False)

publicdb/station_layout/views.py
import datetime

from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render

from ..histograms.models import Configuration
from .forms import ReviewStationLayoutForm, StationLayoutQuarantineForm
from .models import StationLayout, StationLayoutQuarantine

FIRSTDATE = datetime.date(2004, 1, 1)


def layout_submit(request):
    if request.method == 'POST':
        form = StationLayoutQuarantineForm(request.POST)
    else:
        form = StationLayoutQuarantineForm()

    return render(request, 'station_layout/submit.html', {'form': form})


def validate_layout_submit(request):
    if request.method != 'POST':
        return redirect('layout:submit')

    form = StationLayoutQuarantineForm(request.POST)

    if not form.is_valid():
        return layout_submit(request)

    new_layout = StationLayoutQuarantine(
        name=form.cleaned_data['name'],
        email=form.cleaned_data['email'],
        station=form.cleaned_data['station'],
        active_date=form.cleaned_data['active_date'],
        detector_1_alpha=form.cleaned_data['detector_1_alpha'],
        detector_1_beta=form.cleaned_data['detector_1_beta'],
        detector_1_radius=form.cleaned_data['detector_1_radius'],
        detector_1_height=form.cleaned_data['detector_1_height'],
        detector_2_alpha=form.cleaned_data['detector_2_alpha'],
        detector_2_beta=form.cleaned_data['detector_2_beta'],
        detector_2_radius=form.cleaned_data['detector_2_radius'],
        detector_2_height=form.cleaned_data['detector_2_height'],
        detector_3_alpha=form.cleaned_data['detector_3_alpha'],
        detector_3_beta=form.cleaned_data['detector_3_beta'],
        detector_3_radius=form.cleaned_data['detector_3_radius'],
        detector_3_height=form.cleaned_data['detector_3_height'],
        detector_4_alpha=form.cleaned_data['detector_4_alpha'],
        detector_4_beta=form.cleaned_data['detector_4_beta'],
        detector_4_radius=form.cleaned_data['detector_4_radius'],
        detector_4_height=form.cleaned_data['detector_4_height'],
    )

    new_layout.generate_hashes()
    new_layout.save()
    new_layout.sendmail_submit()

    return render(
        request,
        'station_layout/submitted.html',
        {
            'name': form.cleaned_data['name'],
            'email': form.cleaned_data['email'],
            'station': form.cleaned_data['station'],
        },
    )


def confirmed_layout(request, hash):
    submitted_layout = get_object_or_404(StationLayoutQuarantine, hash_submit=hash, email_verified=False)
    submitted_layout.email_verified = True
    submitted_layout.save()
    submitted_layout.sendmail_review()
    return render(request, 'station_layout/confirm.html')


def review_layout(request, hash):
    submitted_layout = get_object_or_404(StationLayoutQuarantine, hash_review=hash, email_verified=True, reviewed=False)
    if request.method == 'POST':
        form = ReviewStationLayoutForm(request.POST)
    else:
        form = ReviewStationLayoutForm()

    try:
        station = submitted_layout.station
        active_date = submitted_layout.active_date.replace(hour=23, minute=59, second=59)
        config = (
            Configuration.objects.filter(
                summary__station=station,
                timestamp__gte=FIRSTDATE,
                timestamp__lte=active_date,
            ).exclude(gps_latitude=0.0)
        ).latest()
    except Configuration.DoesNotExist:
        try:
            configs = Configuration.objects.filter(summary__station=station, timestamp__gte=active_date).exclude(
                gps_latitude=0.0,
            )
            config = configs.earliest()
        except Configuration.DoesNotExist:
            config = None

    return render(
        request,
        'station_layout/review.html',
        {'layout': submitted_layout, 'form': form, 'hash': hash, 'config': config},
    )


def validate_review_layout(request, hash):
    if request.method != 'POST':
        raise Http404

    form = ReviewStationLayoutForm(request.POST)

    if not form.is_valid():
        return review_layout(request)

    submitted_layout = get_object_or_404(StationLayoutQuarantine, hash_review=hash, email_verified=True, reviewed=False)
    submitted_layout.reviewed = True
    submitted_layout.approved = form.cleaned_data['approved']
    submitted_layout.save()

    if form.cleaned_data['approved']:
        accepted_layout = StationLayout(
            station=submitted_layout.station,
            active_date=submitted_layout.active_date,
            detector_1_alpha=submitted_layout.detector_1_alpha,
            detector_1_beta=submitted_layout.detector_1_beta,
            detector_1_radius=submitted_layout.detector_1_radius,
            detector_1_height=submitted_layout.detector_1_height,
            detector_2_alpha=submitted_layout.detector_2_alpha,
            detector_2_beta=submitted_layout.detector_2_beta,
            detector_2_radius=submitted_layout.detector_2_radius,
            detector_2_height=submitted_layout.detector_2_height,
            detector_3_alpha=submitted_layout.detector_3_alpha,
            detector_3_beta=submitted_layout.detector_3_beta,
            detector_3_radius=submitted_layout.detector_3_radius,
            detector_3_height=submitted_layout.detector_3_height,
            detector_4_alpha=submitted_layout.detector_4_alpha,
            detector_4_beta=submitted_layout.detector_4_beta,
            detector_4_radius=submitted_layout.detector_4_radius,
            detector_4_height=submitted_layout.detector_4_height,
        )
        accepted_layout.save()
        submitted_layout.sendmail_accepted()
    else:
        submitted_layout.sendmail_declined()

    return render(request, 'station_layout/reviewed.html')

publicdb/station_layout/templates/station_layout/canvas.html
<canvas id="station_layout" width="600" height="400"></canvas>

<script>
    var canvas = document.getElementById('station_layout');
    var context = canvas.getContext('2d');

    function radians(degrees) {
        return degrees * Math.PI / 180;}

    function draw_gps(ctx) {
        var size = 0.15;
        ctx.fillStyle = 'darkgray';
        ctx.lineWidth = 0;
        ctx.beginPath();
        ctx.arc(0, 0, size, 0, Math.PI * 2, true);
        ctx.closePath();
        ctx.fill();}

    function draw_detector(ctx, r, alpha, beta, color) {
        /* Draw a detector defined by r, alpha, beta coordinates on the canvas
        */
        var detector_width = 0.5;
        var detector_length = 1;
        var pmt_width = 0.04;
        var pmt_length = 0.2;

        ctx.rotate(radians(alpha));
        ctx.translate(0, -r);  // positive y is down on canvas
        ctx.rotate(-radians(alpha));
        ctx.rotate(radians(beta));
        ctx.fillStyle = color;
        ctx.fillRect(-detector_width / 2, -detector_length / 2,
                     detector_width, detector_length);
        ctx.lineWidth = 0.04;
        ctx.strokeRect(-detector_width / 2, -detector_length / 2,
                       detector_width, detector_length);
        // Lightguide and PMT
        ctx.beginPath();
        ctx.moveTo(detector_width / 2, -detector_length / 2);
        ctx.lineTo(pmt_width / 2, -detector_length);
        ctx.lineTo(pmt_width / 2, -(detector_length + pmt_length));
        ctx.lineTo(-pmt_width / 2, -(detector_length + pmt_length));
        ctx.lineTo(-pmt_width / 2, -detector_length);
        ctx.lineTo(-detector_width / 2, -detector_length / 2);
        ctx.stroke();
        ctx.restore();
        ctx.save();}

    function calculate_bounds(r, alpha) {
        /* Calculate the bounding box to contain the detectors and gps
        */
        var min_x = -2, max_x = 2, min_y = -2, max_y = 2;
        var margin = 1.3;  // To ensure the detectors will fit
        for (var i = 0; i < r.length; i++) {
            x = Math.sin(radians(alpha[i])) * r[i];
            min_x = Math.min(x, min_x);
            max_x = Math.max(x, max_x);
            y = Math.cos(radians(alpha[i])) * r[i];
            min_y = Math.min(y, min_y);
            max_y = Math.max(y, max_y);}
        min_x -= margin;
        max_x += margin;
        min_y -= margin;
        max_y += margin;
        return [min_x, max_x, min_y, max_y];}

    function draw_station(ctx, r, alpha, beta) {
        /* Draw a station on the canvas

        r, alpha, beta should be equal length lists with the coordinates.

        Example:
        4-detector station:
        draw_station(context, [8.66, 2.77, 5, 5], [0, 0, -90, 90], [0, 0, 0, 90]);
        2-detector station:
        draw_station(context, [5, 5], [-30, 150], [60, 60]);

        */
        clear_canvas(ctx);
        var colors = ['black', 'Crimson', 'ForestGreen', 'DodgerBlue'];
        var bounds = calculate_bounds(r, alpha);
        var station_width = bounds[1] - bounds[0];
        var station_height = bounds[3] - bounds[2];
        var scale = Math.min(canvas.width / station_width,
                             canvas.height / station_height);
        ctx.scale(scale, scale);
        ctx.translate(-bounds[0], bounds[3]);  // positive y is down on canvas
        ctx.save();
        for (var i = 0; i < r.length; i++) {
            draw_detector(ctx, r[i], alpha[i], beta[i], colors[i]);}
        draw_gps(ctx);}

    function clear_canvas(ctx) {
        /* Clear objects on the canvas and reset origin

        from: https://stackoverflow.com/a/6722031/1033535

        */
        ctx.setTransform(1, 0, 0, 1, 0, 0);
        ctx.clearRect(0, 0, canvas.width, canvas.height);}

</script>

publicdb/station_layout/templates/station_layout/confirm.html
{% extends "base.html" %}

{% block title %}HiSPARC | Station layout submission confirmed{% endblock %}

{% block content %}

    <div id="header">
        <h2>HiSPARC station layout submission confirmed</h2>
    </div>

    <p>
        Your submission has been confirmed and the new layout will be reviewed.<br>
        You will receive an e-mail when the data has been reviewed. Once it
        has been accepted it will be stored in the database with the station.
    </p>

{% endblock %}

publicdb/station_layout/templates/station_layout/review.html
{% extends "base.html" %}

{% load static %}

{% block title %}HiSPARC | Station layout review form{% endblock %}

{% block head_styles %}
<link rel="stylesheet" href="{% static 'styles/submit_form.css' %}">
{% endblock %}

{% block content %}

    <div id="header">
        <h2>HiSPARC station layout review form</h2>
    </div>

    <p>
        This is the submitted station layout for station <strong>{{ layout.station }}</strong>.<br>
        This layout became active on <strong>{{ layout.active_date|date:"Y/m/d H:i" }}</strong>.<br>
        These measurements where submitted by <strong>{{ layout.name }}</strong>.<br>
        The submitter can be reached via: <strong>{{ layout.email }}</strong>.<br>
        Please review the layout and either approve or dismiss it.
        {% if config %}
            <br>It may help to check satellite imagery (from an unknown date) of the station:
            <a target="_blank" href="https://maps.googleapis.com/maps/api/staticmap?center={{ config.gps_latitude }},{{ config.gps_longitude }}&zoom=20&size=640x640&maptype=satellite">Google Static Map</a>.
        {% endif %}
    </p>

    <table>
        <thead>
            <tr>
                <th>
                <th colspan='2'>Primary
                <th colspan='2'>Secondary
            <tr>
                <th>
                <th style="color: black;">1
                <th style="color: red;">2
                <th style="color: green;">3
                <th style="color: blue;">4
        <tbody>
            <tr>
                <td title="radius: distance to detector from GPS, in plane of GPS">r [m]
                <td><input value="{{ layout.detector_1_radius }}" type="number" readonly>
                <td><input value="{{ layout.detector_2_radius }}" type="number" readonly>
                <td><input value="{{ layout.detector_3_radius }}" type="number" readonly>
                <td><input value="{{ layout.detector_4_radius }}" type="number" readonly>
            <tr>
                <td title="alpha: angle between detector and true north as seen from GPS">α [°]
                <td><input value="{{ layout.detector_1_alpha }}" type="number" readonly>
                <td><input value="{{ layout.detector_2_alpha }}" type="number" readonly>
                <td><input value="{{ layout.detector_3_alpha }}" type="number" readonly>
                <td><input value="{{ layout.detector_4_alpha }}" type="number" readonly>
            <tr>
                <td title="height: altitude of the detector above plane of GPS">z [m]
                <td><input value="{{ layout.detector_1_height }}" type="number" readonly>
                <td><input value="{{ layout.detector_2_height }}" type="number" readonly>
                <td><input value="{{ layout.detector_3_height }}" type="number" readonly>
                <td><input value="{{ layout.detector_4_height }}" type="number" readonly>
            <tr>
                <td title="beta: angle of the long side of the scintillator to true north">β [°]
                <td><input value="{{ layout.detector_1_beta }}" type="number" readonly>
                <td><input value="{{ layout.detector_2_beta }}" type="number" readonly>
                <td><input value="{{ layout.detector_3_beta }}" type="number" readonly>
                <td><input value="{{ layout.detector_4_beta }}" type="number" readonly>
    </table>

    {% include "station_layout/canvas.html" %}

    <div style="clear: both;"></div>

    <form style="display: inline-block;" action="{% url 'layout:validate_review' hash=hash %}" method="post">
    {% csrf_token %}
        <input id="id_approved" name="approved" type="hidden" value="1">
        <input type="submit" value="Accept">
    </form>

    <form style="display: inline-block;" action="{% url 'layout:validate_review' hash=hash %}" method="post">
    {% csrf_token %}
        <input type="submit" value="Decline">
    </form>

{% endblock %}

{% block script %}
    {% if layout.detector_3_radius is None %}
        var radius = [{{ layout.detector_1_radius }},
                      {{ layout.detector_2_radius }}]
        var alpha = [{{ layout.detector_1_alpha }},
                     {{ layout.detector_2_alpha }}]
        var beta = [{{ layout.detector_1_beta }},
                    {{ layout.detector_2_beta }}]
    {% else %}
        var radius = [{{ layout.detector_1_radius }},
                      {{ layout.detector_2_radius }},
                      {{ layout.detector_3_radius }},
                      {{ layout.detector_4_radius }}]
        var alpha = [{{ layout.detector_1_alpha }},
                     {{ layout.detector_2_alpha }},
                     {{ layout.detector_3_alpha }},
                     {{ layout.detector_4_alpha }}]
        var beta = [{{ layout.detector_1_beta }},
                    {{ layout.detector_2_beta }},
                    {{ layout.detector_3_beta }},
                    {{ layout.detector_4_beta }}]
    {% endif %}
    draw_station(context, radius, alpha, beta);
{% endblock %}

publicdb/station_layout/templates/station_layout/reviewed.html
{% extends "base.html" %}

{% block title %}HiSPARC | Station layout reviewed{% endblock %}

{% block content %}

    <div id="header">
        <h2>HiSPARC station layout reviewed</h2>
    </div>

    <p>
        Thank you for reviewing the submitted station layout.
    </p>

{% endblock %}

publicdb/station_layout/templates/station_layout/submit.html
{% extends "base.html" %}

{% load static %}

{% block title %}HiSPARC | Station layout submit form{% endblock %}

{% block head_styles %}
<link rel="stylesheet" href="{% static 'styles/submit_form.css' %}">
{% endblock %}

{% block content %}

    <div id="header">
        <h2>HiSPARC station layout submit form</h2>
    </div>

    <div style="float: right;">
        <a href="https://docs.hisparc.nl/publicdb/station_layout.html" target="_blank">
            ➔ Documentation</a><br><br>
        <img width="313" height="250"
             title="HiSPARC station layout coordinate system"
             src="{% static 'images/coordinate_system.png' %}">
    </div>

    <form action="{% url 'layout:validate_submit' %}" method="post">
    {% csrf_token %}
        <p>
            {{ form.name.errors }}
            {{ form.name.label_tag }}
            {{ form.name }}
        </p>
        <p>
            {{ form.email.errors }}
            {{ form.email.label_tag }}
            {{ form.email }}
        </p>
        <p>
            {{ form.station.errors }}
            {{ form.station.label_tag }}
            {{ form.station }}
        </p>
        <p>
            Number of detectors:
            <input name="n" type="radio" value="2"> 2
            <input name="n" type="radio" value="4" checked> 4
        </p>
        <p>
            {{ form.active_date.error }}
            {{ form.active_date.label_tag }}
            {{ form.active_date }}<br>
            <span class="helptext">{{ form.active_date.help_text }}</span>
        </p>
        <table>
            <thead>
                <tr>
                    <th>
                    <th colspan='2'>Primary
                    <th colspan='2'>Secondary
                <tr>
                    <th>
                    <th style="color: black;">1
                    <th style="color: red;">2
                    <th style="color: green;">3
                    <th style="color: blue;">4
            <tbody>
                <tr>
                    <td title="radius: distance to detector from GPS, in plane of GPS">r [m]
                    <td>{{ form.detector_1_radius }}
                    <td>{{ form.detector_2_radius }}
                    <td>{{ form.detector_3_radius }}
                    <td>{{ form.detector_4_radius }}
                <tr>
                    <td title="alpha: angle between detector and true north as seen from GPS">α [°]
                    <td>{{ form.detector_1_alpha }}
                    <td>{{ form.detector_2_alpha }}
                    <td>{{ form.detector_3_alpha }}
                    <td>{{ form.detector_4_alpha }}
                <tr>
                    <td title="height: altitude of the detector above plane of GPS">z [m]
                    <td>{{ form.detector_1_height }}
                    <td>{{ form.detector_2_height }}
                    <td>{{ form.detector_3_height }}
                    <td>{{ form.detector_4_height }}
                <tr>
                    <td title="beta: angle of the long side of the scintillator to true north">β [°]
                    <td>{{ form.detector_1_beta }}
                    <td>{{ form.detector_2_beta }}
                    <td>{{ form.detector_3_beta }}
                    <td>{{ form.detector_4_beta }}
        </table>
        {% include "station_layout/canvas.html" %}

        <div style="clear: both;"></div>
        <input type="submit" value="Submit">
    </form>

{% endblock %}

{% block script %}
    $('form table').on('change', function(event) {
        if ($('input[name=n]:checked').val() == '2') {
            var radius = [Number($('#id_detector_1_radius')[0].value),
                          Number($('#id_detector_2_radius')[0].value)]
            var alpha = [Number($('#id_detector_1_alpha')[0].value),
                         Number($('#id_detector_2_alpha')[0].value)]
            var beta = [Number($('#id_detector_1_beta')[0].value),
                        Number($('#id_detector_2_beta')[0].value)]}
        else {
            var radius = [Number($('#id_detector_1_radius')[0].value),
                          Number($('#id_detector_2_radius')[0].value),
                          Number($('#id_detector_3_radius')[0].value),
                          Number($('#id_detector_4_radius')[0].value)]
            var alpha = [Number($('#id_detector_1_alpha')[0].value),
                         Number($('#id_detector_2_alpha')[0].value),
                         Number($('#id_detector_3_alpha')[0].value),
                         Number($('#id_detector_4_alpha')[0].value)]
            var beta = [Number($('#id_detector_1_beta')[0].value),
                        Number($('#id_detector_2_beta')[0].value),
                        Number($('#id_detector_3_beta')[0].value),
                        Number($('#id_detector_4_beta')[0].value)]}
        draw_station(context, radius, alpha, beta);});

    $('input[name=n]').change(function() {disable_inputs();});

    function disable_inputs() {
        if ($('input[name=n]:checked').val() == '2') {
            $('td:nth-last-child(2) input').prop('disabled', true);
            $('td:last-child input').prop('disabled', true);}
        else {
            $('td:nth-last-child(2) input').prop('disabled', false);
            $('td:last-child input').prop('disabled', false);}}

{% endblock %}