django/controlpanel/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from inforecords.views import *

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^certificaat/genereer/(.+)/(.+).zip$', genereer),
    (r'^maakconfig$', maakconfig),
    (r'^$', direct_to_template, {'template': 'frontpage.html'}),
    (r'^config/nagios$', create_nagios_config),
)

publicdb/raw_data/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'data'
urlpatterns = [
    path('', RedirectView.as_view(url='download', permanent=False)),
    path('download/', views.download_form, name='download_form'),
    path('download/<int:station_number>/<str:start>/<str:end>/', views.download_form, name='download_form'),
    path('download/coincidences/', views.coincidences_download_form, name='coincidences_download_form'),
    path(
        'download/coincidences/<str:start>/<str:end>/',
        views.coincidences_download_form,
        name='coincidences_download_form',
    ),
    path('rpc', views.call_xmlrpc, name='rpc'),
    path('<int:station_number>/events/', views.download_data, {'data_type': 'events'}, name='events'),
    path('<int:station_number>/weather/', views.download_data, {'data_type': 'weather'}, name='weather'),
    path('<int:station_number>/singles/', views.download_data, {'data_type': 'singles'}, name='singles'),
    path(
        'knmi/lightning/<int:lightning_type>/',
        views.download_data,
        {'data_type': 'lightning'},
        name='lightning',
    ),
    path('network/coincidences/', views.download_coincidences, name='coincidences'),
]

publicdb/station_layout/urls.py
from django.urls import path

from . import views

app_name = 'layout'
urlpatterns = [
    path('submit/', views.layout_submit, name='submit'),
    path('submit/validate/', views.validate_layout_submit, name='validate_submit'),
    path('confirm/<slug:hash>/', views.confirmed_layout, name='confirm'),
    path('review/<slug:hash>/', views.review_layout, name='review'),
    path('review/<slug:hash>/validate/', views.validate_review_layout, name='validate_review'),
]

publicdb/status_display/urls.py
from django.urls import include, path, register_converter

from .. import converters
from . import views

register_converter(converters.DateConverter, 'date')

maps_patterns = [
    path('', views.stations_on_map, name='stations_on_map'),
    path('<str:country>/', views.stations_on_map, name='stations_on_map'),
    path('<str:country>/<str:cluster>/', views.stations_on_map, name='stations_on_map'),
    path('<str:country>/<str:cluster>/<str:subcluster>/', views.stations_on_map, name='stations_on_map'),
]

network_patterns = [
    path('coincidences/', views.LatestNetworkSummaryRedirectView.as_view(), name='coincidences'),
    path('coincidences/<date:date>/', views.NetworkSummaryDetailView.as_view(), name='coincidences'),
]

station_patterns = [
    path('<int:station_number>/', views.LatestSummaryRedirectView.as_view(), name='summary'),
    path('<int:station_number>/<date:date>/', views.SummaryDetailView.as_view(), name='summary'),
    path('<int:station_number>/status/', views.station_status, name='status'),
    path('<int:station_number>/config/', views.station_config, name='config'),
    path('<int:station_number>/latest/', views.station_latest, name='latest'),
]

source_patterns = [
    *[
        # Network histograms
        path(
            f'{type}/<date:date>/',
            views.get_specific_network_histogram_source,
            {'type': type},
            name=type,
        )
        for type in [
            'coincidencetime',
            'coincidencenumber',
        ]
    ],
    *[
        # Histograms
        path(
            f'{type}/<int:station_number>/<date:date>/',
            views.get_specific_histogram_source,
            {'type': type},
            name=type,
        )
        for type in [
            'eventtime',
            'pulseheight',
            'pulseintegral',
            'singleslow',
            'singleshigh',
            'zenith',
            'azimuth',
        ]
    ],
    *[
        # Datasets
        path(
            f'{type}/<int:station_number>/<date:date>/',
            views.get_specific_dataset_source,
            {'type': type},
            name=type,
        )
        for type in [
            'barometer',
            'temperature',
            'singlesratelow',
            'singlesratehigh',
        ]
    ],
    *[
        # Configurations
        path(
            f'{type}/<int:station_number>/',
            views.get_specific_config_source,
            {'type': type},
            name=type,
        )
        for type in [
            'electronics',
            'voltage',
            'current',
            'gps',
            'trigger',
        ]
    ],
    *[
        # Histograms
        path('eventtime/<int:station_number>/', views.get_eventtime_source, name='eventtime'),
        # Configurations
        path('layout/<int:station_number>/', views.get_station_layout_source, name='layout'),
        # Calibrations
        path(
            'detector_timing_offsets/<int:station_number>/',
            views.get_detector_timing_offsets_source,
            name='detector_offsets',
        ),
        path(
            'station_timing_offsets/<int:ref_station_number>/<int:station_number>/',
            views.get_station_timing_offsets_source,
            name='station_offsets',
        ),
    ],
]

app_name = 'status'
urlpatterns = [
    path('stations/', views.stations, name='stations'),
    path('stations_by_country/', views.stations_by_country, name='stations_by_country'),
    path('stations_by_name/', views.stations_by_name, name='stations_by_name'),
    path('stations_by_number/', views.stations_by_number, name='stations_by_number'),
    path('stations_by_status/', views.stations_by_status, name='stations_by_status'),
    path('stations_on_map/', include((maps_patterns, 'map'))),
    path('network/', include((network_patterns, 'network'))),
    path('stations/', include((station_patterns, 'station'))),
    path('source/', include((source_patterns, 'source'))),
    path('help/', views.help, name='help'),
]

publicdb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView

from .inforecords.views import create_datastore_config

urlpatterns = [
    path('', RedirectView.as_view(url='show/stations', permanent=False)),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('api/', include('publicdb.api.urls')),
    path('show/', include('publicdb.status_display.urls')),
    path('maps/', include('publicdb.maps.urls')),
    path('layout/', include('publicdb.station_layout.urls')),
    path('analysis-session/', include('publicdb.analysissessions.urls')),
    path('software-updates/', include('publicdb.updates.urls')),
    path('raw_data/', include('publicdb.raw_data.urls', namespace='raw_data')),
    path('data/', include('publicdb.raw_data.urls')),
    path('config/datastore', create_datastore_config, name='datastore_config'),
    path('admin/', admin.site.urls),
]

publicdb/status_display/views.py
import calendar
import csv
import datetime

from collections import OrderedDict
from io import StringIO
from itertools import groupby
from operator import itemgetter

from numpy import arange, nan

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, redirect, render
from django.views.generic import DateDetailView, RedirectView

from sapphire.transformations import clock

from ..histograms.models import (
    Configuration,
    DailyDataset,
    DailyHistogram,
    DetectorTimingOffset,
    MultiDailyDataset,
    MultiDailyHistogram,
    NetworkHistogram,
    NetworkSummary,
    StationTimingOffset,
    Summary,
)
from ..inforecords.models import Cluster, Country, Station
from ..raw_data.date_generator import daterange
from ..station_layout.models import StationLayout
from .status import DataStatus

FIRSTDATE = datetime.date(2004, 1, 1)
MIME_TSV = 'text/tab-separated-values'


def stations(request):
    """Show the default station list"""

    return redirect('status:stations_by_country')


def stations_by_country(request):
    """Show a list of stations, ordered by country, cluster and subcluster"""

    station_status = DataStatus()
    statuscount = station_status.get_status_counts()

    data_stations = stations_with_data()

    countries = OrderedDict()
    test_stations = []

    for station in Station.objects.all().select_related(
        'cluster__country',
        'cluster__parent',
    ):
        link = station in data_stations
        status = station_status.get_status(station.number)

        station_info = {'number': station.number, 'name': station.name, 'link': link, 'status': status}

        country = station.cluster.country.name
        if station.cluster.parent:
            cluster = station.cluster.parent.name
        else:
            cluster = station.cluster.name
        subcluster = station.cluster.name

        if len(station.pcs.filter(is_test=True)):
            test_stations.append(station_info)
            continue
        if country not in countries:
            countries[country] = OrderedDict()
        if cluster not in countries[country]:
            countries[country][cluster] = OrderedDict()
        if subcluster not in countries[country][cluster]:
            countries[country][cluster][subcluster] = []
        countries[country][cluster][subcluster].append(station_info)

    return render(
        request,
        'status_display/stations_by_country.html',
        {'countries': countries, 'test_stations': test_stations, 'statuscount': statuscount},
    )


def stations_by_number(request):
    """Show a list of stations, ordered by number"""

    station_status = DataStatus()
    statuscount = station_status.get_status_counts()

    data_stations = stations_with_data()
    stations = []
    for station in Station.objects.all():
        link = station in data_stations
        status = station_status.get_status(station.number)

        stations.append({'number': station.number, 'name': station.name, 'link': link, 'status': status})

    return render(request, 'status_display/stations_by_number.html', {'stations': stations, 'statuscount': statuscount})


def stations_by_status(request):
    """Show a list of stations, ordered by status"""

    station_status = DataStatus()
    statuscount = station_status.get_status_counts()

    data_stations = stations_with_data()
    # keep a specific ordering of the status labels
    station_groups = OrderedDict([('up', []), ('problem', []), ('down', []), ('unknown', [])])
    for station in Station.objects.all():
        link = station in data_stations
        status = station_status.get_status(station.number)

        # use setdefault() to automatically include unforeseen status labels without crashing
        group = station_groups.setdefault(status, [])
        group.append({'number': station.number, 'name': station.name, 'link': link, 'status': status})

    return render(
        request,
        'status_display/stations_by_status.html',
        {'station_groups': station_groups, 'statuscount': statuscount},
    )


def stations_by_name(request):
    """Show a list of stations, ordered by station name"""

    station_status = DataStatus()
    statuscount = station_status.get_status_counts()

    data_stations = stations_with_data()
    stations = []
    for station in Station.objects.all():
        link = station in data_stations
        status = station_status.get_status(station.number)

        stations.append({'number': station.number, 'name': station.name, 'link': link, 'status': status})

    stations = sorted(stations, key=itemgetter('name'))

    return render(request, 'status_display/stations_by_name.html', {'stations': stations, 'statuscount': statuscount})


def get_focus(country=None, cluster=None, subcluster=None):
    if not country:
        return Cluster.objects.all().values_list('name', flat=True)

    country = get_object_or_404(Country, name=country)

    if not cluster:
        return country.clusters.values_list('name', flat=True)

    cluster = get_object_or_404(country.clusters, name=cluster, parent=None)

    if not subcluster:
        focus = [cluster.name]
        focus.extend(cluster.subclusters.values_list('name', flat=True))
        return focus

    if cluster.name == subcluster:
        return [cluster.name]

    subcluster = get_object_or_404(cluster.subclusters, name=subcluster)

    return [subcluster.name]


def stations_on_map(request, country=None, cluster=None, subcluster=None):
    """Show all stations from a subcluster on a map"""

    focus = get_focus(country, cluster, subcluster)

    data_stations = stations_with_data()
    station_status = DataStatus()
    statuscount = station_status.get_status_counts()

    subclusters = []
    for subcluster_object in Cluster.objects.all():
        stations = []
        for station in subcluster_object.stations.filter(pcs__is_test=False).distinct():
            link = station in data_stations
            status = station_status.get_status(station.number)

            location = station.latest_location()
            station_data = {
                'number': station.number,
                'name': station.name,
                'cluster': subcluster_object,
                'link': link,
                'status': status,
            }
            station_data.update(location)
            stations.append(station_data)
        subclusters.append({'name': subcluster_object.name, 'stations': stations})

    return render(
        request,
        'status_display/stations_on_map.html',
        {'subclusters': subclusters, 'focus': focus, 'statuscount': statuscount},
    )


class NetworkSummaryDetailView(DateDetailView):
    http_method_names = ['get']
    template_name = 'status_display/network_coincidences.html'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        date = self.kwargs['date']

        try:
            obj = queryset.get(date=date)
        except queryset.model.DoesNotExist:
            raise Http404

        return obj

    def get_queryset(self):
        return NetworkSummary.objects.with_coincidences().prefetch_related(
            'network_histograms',
            'network_histograms__type',
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date = self.object.date

        # Find previous/next dates with data
        try:
            prev = NetworkSummary.objects.with_coincidences().filter(date__lt=date).latest().date
        except NetworkSummary.DoesNotExist:
            prev = None

        try:
            next = NetworkSummary.objects.with_coincidences().filter(date__gt=date).earliest().date
        except NetworkSummary.DoesNotExist:
            next = None

        # Number of non-test stations with data on this date
        n_stations = (
            Station.objects.filter(summaries__date=date, summaries__num_events__isnull=False, pcs__is_test=False)
            .distinct()
            .count()
        )
        histograms = DailyHistogram.objects.filter(
            summary__date=date,
            summary__station__pcs__is_test=False,
            type__slug='eventtime',
        ).distinct()
        number_of_events = sum(sum(histogram.values) for histogram in histograms)
        status = {'station_count': n_stations, 'n_events': number_of_events}

        # Date navigation
        thismonth = self.nav_calendar()
        month_list = self.nav_months()
        year_list = self.nav_years()

        # Data for the plots
        plots = {histogram.type.slug: plot_histogram(histogram) for histogram in self.object.network_histograms.all()}

        # data for singles plots
        singles_datasets = MultiDailyDataset.objects.filter(
            summary__date=date,
            summary__station__pcs__is_test=False,
            type__slug='singlesratelow',
        ).distinct()
        singles_plots = [(dataset.summary.station.number, plot_dataset(dataset)) for dataset in singles_datasets]
        singles_plots = sorted(singles_plots)

        context.update(
            {
                'date': date,
                'tomorrow': date + datetime.timedelta(days=1),
                'status': status,
                'plots': plots,
                'singles_plots': singles_plots,
                'thismonth': thismonth,
                'month_list': month_list,
                'year_list': year_list,
                'prev': prev,
                'next': next,
            },
        )
        return context

    def nav_calendar(self):
        """Create a month calendar with links"""

        date = self.object.date

        month = calendar.Calendar().monthdatescalendar(date.year, date.month)

        days_with_data = self.get_queryset().filter(date__year=date.year, date__month=date.month)

publicdb/status_display/templates/status_display/base_network.html
{% extends 'base.html' %}

{% load static %}

{% block head_styles %}
    <link rel="stylesheet" href="{% static 'styles/station_page.css' %}">
{% endblock %}

{% block title %}
    HiSPARC Network - {{ date|date:"D, j N Y" }}
{% endblock %}

{% block content %}

    <div id="header">
        <h1>{% block header %}HiSPARC Network{% endblock %}</h1>
        <div id="date">{% block date %}{% now "D, j N Y" %}{% endblock %}</div>
    </div>

    {% block data %}
    {% endblock %}

    <div id="sidebar">
        <div id="navigation">
          {% block navigation_sidebar %}
            <div class="keyvalue">
                <span class="key">Stations</span>
                <span class="value"><a href="{% url 'status:stations' %}">List</a></span>
                <span class="value"><a href="{% url 'status:map:stations_on_map' %}">Map</a></span>
                <span class="value"><a class="{% block current_coincidences %}{% endblock %}" href="{% url 'status:network:coincidences' %}">Network</a></span>
            </div>
          {% endblock %}
        </div>

        <div id="status">
          {% block status %}{% endblock %}
        </div>

        <div id="help">
          {% block help %}
            <div class="keyvalue">
                <span class="value"><a href="{% url 'status:help' %}" target="_blank">Help</a></span>
            </div>
          {% endblock %}
        </div>
    </div>

{% endblock %}

publicdb/status_display/templates/status_display/base_station.html
{% extends 'base.html' %}

{% load static %}

{% block head_styles %}
    <link rel="stylesheet" href="{% static 'styles/station_page.css' %}">
{% endblock %}

{% block title %}
    HiSPARC Station: {{ station.number }} - {{ station.name }}
{% endblock %}

{% block content %}

    <div id="header">
        <h1>{% block header %}Station: {{ station.number }} &mdash; {{ station.name }}{% endblock %}</h1>
        <div id="date">{% block date %}{% now "D, j N Y" %}{% endblock %}</div>
    </div>

    {% block data %}
    {% endblock %}

    <div id="sidebar">
        <div id="navigation">
          {% block navigation_sidebar %}
            <div class="keyvalue">
                <span class="key">Stations</span>
                <span class="value"><a href="{% url 'status:stations' %}">List</a></span>
                <span class="value"><a href="{% url 'status:map:stations_on_map' %}">Map</a></span>
                <span class="value {% if not coincidences_found %}nolink">Coincidences</span>{% else %}"><a class="{% block current_coincidences %}{% endblock %}" href="{% block current_date %}{% url 'status:network:coincidences' %}{% endblock %}">Network</a></span>{% endif %}
            </div>

            <div class="keyvalue"><span class="key">Station</span>
                <span class="value {% if not has_data %}nolink">Data</span>{% else %}"><a class="{% block current_data %}{% endblock %}" href="{% url 'status:station:summary' station_number=station.number %}">Data</a></span>{% endif %}
                <span class="value"><a class="{% block current_status %}{% endblock %}" href="{% url 'status:station:status' station_number=station.number %}">Status</a></span>
                <span class="value {% if not has_config %}nolink">Config</a></span>{% else %}"><a class="{% block current_config %}{% endblock %}" href="{% url 'status:station:config' station_number=station.number %}">Config</a></span>{% endif %}
            </div>
          {% endblock %}
        </div>

        <div id="config">
          {% block config %}{% endblock %}
        </div>

        <div id="help">
          {% block help %}
            <div class="keyvalue">
                <span class="value"><a href="{% url 'status:help' %}" target="_blank">Help</a></span>
            </div>
          {% endblock %}
        </div>
    </div>

{% endblock %}

publicdb/status_display/templates/status_display/base_stations.html
{% extends 'base.html' %}

{% load static %}

{% block head_styles %}
    <link rel="stylesheet" href="{% static 'styles/stations.css' %}">
{% endblock %}

{% block content %}

    <div id="header">
        <h1>{% block header %}List of HiSPARC stations{% endblock %}</h1>
    </div>

    <div id="stationList">
      {% block list %}{% endblock %}
    </div>

    {% block map %}{% endblock %}

    <div id="sidebar">
        <div id="navigation">
          {% block navigation_sidebar %}
            <div class="sectionTitle">Stations</div>
            <div class="keyvalue">
                <span class="key">List by</span>
                <span class="value"><a class="{% block current_location %}{% endblock %}" href="{% url 'status:stations_by_country' %}">Location</a></span>
                <span class="value"><a class="{% block current_name %}{% endblock %}" href="{% url 'status:stations_by_name' %}">Name</a></span>
                <span class="value"><a class="{% block current_number %}{% endblock %}" href="{% url 'status:stations_by_number' %}">Number</a></span>
                <span class="value"><a class="{% block current_status %}{% endblock %}" href="{% url 'status:stations_by_status' %}">Status</a></span>
            </div>
            <div class="keyvalue">
                <span class="key">Map</span>
                <span class="value"><a class="{% block current_map %}{% endblock %}" href="{% url 'status:map:stations_on_map' %}">Overview</a></span>
            </div>
            <div class="keyvalue">
                <span class="key">Data</span>
                <span class="value"><a href="{% url 'status:network:coincidences' %}">Network</a></span>
            </div>
          {% endblock %}
        </div>

        <div id="legend">
          {% block legend %}
            <div class="sectionTitle">Data availability</div>
            <div class="keyvalue">
                <span class="key thin" style='color: #23B;'>Station</span>
                <span class="value">&larr; Link to data</span><br>
            </div>
            <div class="keyvalue">
                <span class="key thin">Station</span>
                <span class="value">No data received</span>
            </div>


            <div class="sectionTitle">Recent data</div>
            <div class="keyvalue">
                <span class='key statusBall up'></span>
                <span class="value">Up: Received data yesterday {% if statuscount %}({{ statuscount.up }}){% endif %}</span><br>
            </div>
            <div class="keyvalue">
                <span class='key statusBall problem'></span>
                <span class="value">Problem: No data yesterday {% if statuscount %}({{ statuscount.problem }}){% endif %}</span><br>
            </div>
            <div class="keyvalue">
                <span class='key statusBall down'></span>
                <span class="value">Down: No recent data {% if statuscount %}({{ statuscount.down }}){% endif %}</span><br>
            </div>
            <div class="keyvalue">
                <span class='key statusBall unknown'></span>
                <span class="value">Unknown</span><br>
            </div>
            <div class="keyvalue">
                <span class='key statusBall'></span>
                <span class="value">&larr; Link to most recent data</span>
            </div>

            <div class="sectionTitle">Region map</div>
            <div class="keyvalue">
                <span class="key">Cluster</span>
                <span class="value">&larr; Link to map</span><br>
            </div>
          {% endblock %}
        </div>

        <div id="extra">
          {% block extra %}{% endblock %}
        </div>

        <div id="help">
          {% block help %}
            <div class="keyvalue">
                <span class="value"><a href="{% url 'status:help' %}" target="_blank">Help</a></span>
            </div>
          {% endblock %}
        </div>
    </div>

{% endblock %}

publicdb/status_display/templates/status_display/network_coincidences.html
{% extends 'status_display/base_network.html' %}

{% load fix_data %}
{% load static %}

{% block current_coincidences %}currentPage{% endblock %}

{% block head %}
    <script src="{% static 'scripts/flot_settings.js' %}"></script>
    <script>
        function downloadGraph(target) {
            var dataurl = $(target + ' .flot-base')[0].toDataURL();
            window.open(dataurl, '_blank', "height=350, width=630, toolbar=yes")
        }
    </script>
{% endblock %}

{% block date %}{{ date|date:"D, j N Y" }}{% endblock %}

{% block data %}
    <div id="graphs">

      {% if plots.coincidencetime %}
        <div id="coincidenceTimeHistogram" class="histogram">
            <h3>Coincidence histogram (number of coincidences per hour)</h3>
            <div class="sourceLink">
                <a onclick="downloadGraph('#ct_histogram')">Image</a> |
                <a href="{% url 'status:source:coincidencetime' date=date %}">Source</a>
            </div>
            <div class="plot" id="ct_histogram"></div>
            <script>
                ct_labels = {yaxis: {axisLabel: "{{ plots.coincidencetime.y_label }}"},
                             xaxis: {axisLabel: "{{ plots.coincidencetime.x_label }}"}}
                $.extend(true, ct_options, ct_labels)
                $.plot($("#ct_histogram"), [
                  {% for data in plots.coincidencetime.data %}
                    {data: {{ data|fix_histogram_data }}, yaxis: 1},
                  {% endfor %}
                    {data: [0, 0], lines: {show: false}, xaxis: 2, yaxis: 2},], ct_options);
            </script>
        </div>
      {% endif %}

      {% if plots.coincidencenumber %}
        <div id="coincidenceNumberHistogram" class="histogram">
            <h3>Number of stations histogram</h3>
            <div class="sourceLink">
                <a onclick="downloadGraph('#cn_histogram')">Image</a> |
                <a href="{% url 'status:source:coincidencenumber' date=date %}">Source</a>
            </div>
            <div class="plot" id="cn_histogram"></div>
            <script>
                cn_labels = {yaxis: {axisLabel: "{{ plots.coincidencenumber.y_label }}"},
                             xaxis: {axisLabel: "{{ plots.coincidencenumber.x_label }}"}}
                $.extend(true, cn_options, cn_labels)
                $.plot($("#cn_histogram"), [
                  {% for data in plots.coincidencenumber.data %}
                    {data: {{ data|fix_histogram_data|shift_bins:-0.5 }}, yaxis: 1},
                  {% endfor %}
                    {data: [0, 0], lines: {show: false}, xaxis: 2, yaxis: 2},], cn_options);
            </script>
        </div>
      {% endif %}

    {% for station_number, plot in singles_plots %}
      <div id="singlesratelowData_{{ station_number }}" class="histogram">
          <h3>Station {{ station_number }}: Singles (per second above low threshold)</h3>
          <div class="singlesplot" id="srl_{{ station_number }}"></div>
          <script>
              srl_labels = {yaxis: {axisLabel: "{{ plot.y_label }}"},
                           xaxis: {axisLabel: "{{ plot.x_label }}"}}
              $.extend(true, srl_options, srl_labels)
              $.plot($("#srl_{{ station_number }}"), [
                {% for data in plot.data %}
                  {data: {{ data|fix_timestamps_in_data|slice_data:50|round_data:2 }}, yaxis: 1},
                {% endfor %}
                  {data: [0, 0], lines: {show: false}, xaxis: 2, yaxis: 2},], srl_options);
          </script>
      </div>
    {% endfor %}
    </div>
{% endblock %}

{% block navigation_sidebar %}
    {{ block.super }}

    <div id="download"><a href="{% url 'data:coincidences_download_form' start=date.isoformat end=tomorrow.isoformat %}">Download event summary data</a></div>

  {% if prev %}
     <a class='nextprev' id='prev' href="{% url 'status:network:coincidences' date=prev %}">&larr;</a>
  {% endif %}
  {% if next %}
     <a class='nextprev' id='next' href="{% url 'status:network:coincidences' date=next %}">&rarr;</a>
  {% endif %}

    <table id="calendar">
    <tr><th colspan="7">{{ date|date:"F Y" }}</th></tr>
    <tr>
      {% for day in thismonth.days %}
        <th class="dayname">{{ day }}</th>
      {% endfor %}
    </tr>
      {% for week in thismonth.weeks %}
        <tr>
          {% for day in week %}
            <td class="day">
              {% if day.link %}
                <a {% if date.day == day.day %}class='currentDate'{% endif %} href="{{ day.link }}">{{ day.day }}</a>
              {% else %}
                <span class="nolink">{{ day.day }}</span>
              {% endif %}
            </td>
          {% endfor %}
        </tr>
      {% endfor %}
    </table>

    <div id="monthlist">
    <ul>
      {% for month in month_list %}
        <li>
          {% if month.link %}
            <a {% if date.month == month.month %}class='currentDate'{% endif %} href="{{ month.link }}">{{ month.month }}</a>
          {% else %}
            <span class="nolink">{{ month.month }}</span>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
    </div>

    <div id="yearlist">
    <ul>
      {% for year in year_list %}
        <li>
          {% if year.link %}
            <a {% if date.year == year.year %}class='currentDate'{% endif %} href="{{ year.link }}">{{ year.year }}</a>
          {% else %}
            <span class="nolink">{{ year.year }}</span>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
    </div>
{% endblock %}

{% block status %}
  {% if status %}
    <div id="stations">
        <div class="sectionTitle">Source</div>
        <div class="keyvalue"><span class="key">Stations with data</span><span class="value">{{ status.station_count }}</span></div>
        <div class="keyvalue"><span class="key">Total number of events</span><span class="value">{{ status.n_events }}</span></div>
    </div>
  {% endif %}
{% endblock %}